SET search_path = public;

DO $$ BEGIN CREATE TYPE public.bast_status AS ENUM ('draft','issued','approved','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.checklist_status AS ENUM ('todo','in_progress','done','na'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.izin_jenis AS ENUM ('cuti_tahunan','cuti_sakit','dinas_luar','wfh','lainnya'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.izin_status AS ENUM ('pending','approved','rejected','dibatalkan'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.job_status AS ENUM ('pending','running','success','failed','dead'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.metode_susut AS ENUM ('garis_lurus','saldo_menurun'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.mutasi_status AS ENUM ('pending','approved','rejected','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.retry_status AS ENUM ('pending','retrying','success','dead_letter','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.shift_jenis AS ENUM ('pagi','malam','khusus'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.sla_event_type AS ENUM ('pause','resume','reset'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.submission_status AS ENUM ('draft','submitted','approved','rejected','revision'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.uat_result_status AS ENUM ('pass','partial','fail'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.aset_bast (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nomor text NOT NULL, pemberi_user uuid, penerima_user uuid, opd_id uuid, tanggal date DEFAULT CURRENT_DATE NOT NULL, catatan text, status text DEFAULT 'issued' NOT NULL, created_by uuid, approved_by uuid, approved_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.aset_bast_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), bast_id uuid NOT NULL, aset_id uuid NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.aset_mutasi (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), aset_id uuid NOT NULL, dari_user uuid, ke_user uuid, dari_opd uuid, ke_opd uuid, alasan text, diajukan_oleh uuid, status text DEFAULT 'pending' NOT NULL, catatan text, ttd_url text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, approved_by uuid, approved_at timestamptz, catatan_approval text);
CREATE TABLE IF NOT EXISTS public.aset_opname (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, periode text NOT NULL, status text DEFAULT 'open' NOT NULL, catatan text, dibuat_oleh uuid, ditutup_oleh uuid, closed_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.aset_opname_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opname_id uuid NOT NULL, aset_id uuid NOT NULL, hadir boolean, kondisi_temuan text, catatan text, verified_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.aset_pemeliharaan (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), aset_id uuid NOT NULL, opd_id uuid, jenis text, deskripsi text, jadwal date, selesai_at timestamptz, biaya numeric DEFAULT 0, vendor text, status text DEFAULT 'dijadwalkan' NOT NULL, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.aset_penyusutan_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), aset_id uuid NOT NULL, periode text NOT NULL, susut_bulan numeric DEFAULT 0 NOT NULL, akumulasi numeric DEFAULT 0 NOT NULL, nilai_buku numeric DEFAULT 0 NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.aset_verification_campaign (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nama text NOT NULL, opd_id uuid, status text DEFAULT 'open' NOT NULL, catatan text, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, deskripsi text, periode_mulai date, periode_selesai date, target_opd_ids uuid[] DEFAULT '{}' NOT NULL);
CREATE TABLE IF NOT EXISTS public.aset_verification_item (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid NOT NULL, aset_id uuid NOT NULL, verified boolean DEFAULT false, kondisi text, catatan text, verified_by uuid, verified_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, opd_id uuid, status text DEFAULT 'belum' NOT NULL, lat numeric, lng numeric, lokasi_text text, foto_url text);
CREATE TABLE IF NOT EXISTS public.attendance_shift_assignment (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, shift_id uuid NOT NULL, dari date NOT NULL, sampai date, aktif boolean DEFAULT true NOT NULL, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.attendance_shifts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, nama text NOT NULL, jam_masuk time NOT NULL, jam_pulang time NOT NULL, toleransi_menit integer DEFAULT 15 NOT NULL, jenis text DEFAULT 'pagi' NOT NULL, aktif boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.compliance_checklist (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), domain text NOT NULL, kode text NOT NULL, label text NOT NULL, status text DEFAULT 'todo' NOT NULL, bukti_url text, catatan text, updated_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, judul text, deskripsi text);
CREATE TABLE IF NOT EXISTS public.consent_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, consent_type text NOT NULL, version text DEFAULT 'v1' NOT NULL, granted boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.cron_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_name text NOT NULL, status text DEFAULT 'running' NOT NULL, request_id text, started_at timestamptz DEFAULT now() NOT NULL, finished_at timestamptz, duration_ms integer, affected_rows integer, error text, meta jsonb DEFAULT '{}', created_at timestamptz DEFAULT now() NOT NULL, detail jsonb);
CREATE TABLE IF NOT EXISTS public.dataset_submission (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), template_id uuid, user_id uuid NOT NULL, opd_id uuid, data jsonb DEFAULT '{}' NOT NULL, status text DEFAULT 'draft' NOT NULL, catatan_review text, reviewed_by uuid, reviewed_at timestamptz, submitted_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, oleh_user_id uuid, review_status text DEFAULT 'pending' NOT NULL, review_note text);
CREATE TABLE IF NOT EXISTS public.dataset_submission_review (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL, reviewer_id uuid NOT NULL, action text NOT NULL, catatan text, created_at timestamptz DEFAULT now() NOT NULL, aksi text);
CREATE TABLE IF NOT EXISTS public.dataset_template (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), judul text NOT NULL, deskripsi text, target_role text DEFAULT 'asn' NOT NULL, target_scope text DEFAULT 'opd_sendiri' NOT NULL, target_opd_ids uuid[] DEFAULT '{}', kolom jsonb DEFAULT '[]' NOT NULL, deadline timestamptz, aktif boolean DEFAULT true NOT NULL, allow_multiple_submit boolean DEFAULT false NOT NULL, excel_layout jsonb DEFAULT '{"group_by":"opd","sheet_name":"Rangkuman"}', created_by uuid, opd_id uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, kode text, opd_pemilik_id uuid);
CREATE TABLE IF NOT EXISTS public.dead_letter_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_name text NOT NULL, payload jsonb DEFAULT '{}', error_message text, retry_count integer DEFAULT 0 NOT NULL, resolved_at timestamptz, resolved_by uuid, request_id text, created_at timestamptz DEFAULT now() NOT NULL, failed_at timestamptz DEFAULT now() NOT NULL, replayed_to uuid, resolution_note text);
CREATE TABLE IF NOT EXISTS public.digital_signatures (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, signature_path text NOT NULL, is_active boolean DEFAULT true NOT NULL, revoked_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.document_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), document_id uuid NOT NULL, action text NOT NULL, actor uuid, metadata jsonb DEFAULT '{}' NOT NULL, ip_hash text, user_agent text, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, document_type text NOT NULL, generated_by_system boolean DEFAULT false NOT NULL, source_module text, source_ref_id uuid, file_path text NOT NULL, opd_id uuid, created_by uuid NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.dokumen_verifikasi (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), permohonan_id uuid, storage_path text NOT NULL, jenis text, hash text, size_bytes bigint, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, token text, nomor_surat text, sha256 text, signature_provider text, diterbitkan_oleh uuid);
CREATE TABLE IF NOT EXISTS public.escalation_config (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, layanan_id uuid, threshold_hours integer DEFAULT 48 NOT NULL, action text DEFAULT 'notify' NOT NULL, target_user_id uuid, aktif boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, level integer DEFAULT 1 NOT NULL, threshold_days integer DEFAULT 2 NOT NULL, target_role text DEFAULT 'admin_opd' NOT NULL);
CREATE TABLE IF NOT EXISTS public.feature_flags (key text PRIMARY KEY, enabled boolean DEFAULT true NOT NULL, description text, updated_by uuid, updated_at timestamptz DEFAULT now() NOT NULL, flag_key text);
CREATE TABLE IF NOT EXISTS public.form_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid NOT NULL, user_id uuid, opd_id uuid, status text DEFAULT 'pending' NOT NULL, assigned_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, version_number integer DEFAULT 1 NOT NULL, due_at timestamptz, assigned_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.form_fields (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid NOT NULL, kode text NOT NULL, label text NOT NULL, tipe text DEFAULT 'text' NOT NULL, urutan integer DEFAULT 0 NOT NULL, required boolean DEFAULT false NOT NULL, options jsonb DEFAULT '[]', help text, created_at timestamptz DEFAULT now() NOT NULL, visible_if jsonb, placeholder text, help_text text, validation jsonb DEFAULT '{}');
CREATE TABLE IF NOT EXISTS public.form_submission_comment (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL, oleh uuid, pesan text NOT NULL, internal_only boolean DEFAULT false NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.form_submission_files (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL, field_kode text, storage_path text NOT NULL, provider text DEFAULT 'supabase' NOT NULL, mime text, size_bytes bigint, cleanup_status text DEFAULT 'ok', created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, uploaded_by uuid, finalized_at timestamptz);
CREATE TABLE IF NOT EXISTS public.form_submission_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL, version integer DEFAULT 1 NOT NULL, data jsonb DEFAULT '{}' NOT NULL, files jsonb DEFAULT '[]', created_by uuid, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.form_submissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid NOT NULL, user_id uuid, opd_id uuid, data jsonb DEFAULT '{}' NOT NULL, status text DEFAULT 'draft' NOT NULL, assignment_id uuid, submitted_at timestamptz, reviewed_at timestamptz, reviewed_by uuid, version_number integer DEFAULT 1 NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, schema_version_snapshot jsonb, review_note text);
CREATE TABLE IF NOT EXISTS public.form_targets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid NOT NULL, target_type text NOT NULL, target_id uuid, created_at timestamptz DEFAULT now() NOT NULL, target_value text);
CREATE TABLE IF NOT EXISTS public.forms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), judul text NOT NULL, deskripsi text, opd_pemilik_id uuid, status text DEFAULT 'draft' NOT NULL, schema_snapshot jsonb DEFAULT '{}', slug text, is_public boolean DEFAULT false NOT NULL, published_at timestamptz, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, deadline timestamptz, allow_multiple_submit boolean DEFAULT false NOT NULL, published_by uuid, archived_at timestamptz);
CREATE TABLE IF NOT EXISTS public.geofence_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid, opd_id uuid, lat numeric, lng numeric, dist_m numeric, radius_m numeric, valid boolean, reason text, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.hari_libur (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tanggal date NOT NULL, nama text NOT NULL, jenis text DEFAULT 'nasional' NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, nasional boolean DEFAULT true NOT NULL, catatan text);
CREATE TABLE IF NOT EXISTS public.ikm_responses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), survey_id uuid NOT NULL, permohonan_id uuid, user_id uuid, u1 integer, u2 integer, u3 integer, u4 integer, u5 integer, u6 integer, u7 integer, u8 integer, u9 integer, saran text, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.ikm_surveys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, layanan_id uuid, judul text NOT NULL, aktif boolean DEFAULT true NOT NULL, mulai date, selesai date, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, periode text, created_by uuid);
CREATE TABLE IF NOT EXISTS public.leave_balances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, tahun integer NOT NULL, jenis text NOT NULL, kuota integer DEFAULT 0 NOT NULL, terpakai integer DEFAULT 0 NOT NULL, catatan text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.lokasi_gedung (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nama text NOT NULL, alamat text, opd_id uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.lokasi_lantai (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), gedung_id uuid NOT NULL, nama text NOT NULL, urutan integer DEFAULT 0 NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.lokasi_ruangan (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lantai_id uuid NOT NULL, nama text NOT NULL, kode text, pic_user_id uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.nomor_surat_issued (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nomor text NOT NULL, tahun integer NOT NULL, opd_id uuid, permohonan_id uuid, issued_at timestamptz DEFAULT now() NOT NULL, issued_by uuid, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.nomor_surat_sequence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, tahun integer NOT NULL, last_number integer DEFAULT 0 NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, tipe text NOT NULL, judul text NOT NULL, body text, link text, meta jsonb DEFAULT '{}', dibaca boolean DEFAULT false NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.overtime_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, opd_id uuid, tanggal date NOT NULL, jam_mulai time NOT NULL, jam_selesai time NOT NULL, alasan text, status text DEFAULT 'pending' NOT NULL, approved_by uuid, catatan_approval text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, approved_at timestamptz);
CREATE TABLE IF NOT EXISTS public.payroll_periods (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, tahun integer NOT NULL, bulan integer NOT NULL, locked_at timestamptz, locked_by uuid, unlocked_at timestamptz, unlocked_by uuid, catatan text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.pengajuan_izin (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, opd_id uuid, jenis text NOT NULL, dari date NOT NULL, sampai date NOT NULL, alasan text, lampiran_url text, status text DEFAULT 'pending' NOT NULL, approved_by uuid, catatan_approval text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, approved_at timestamptz, mengurangi_saldo boolean DEFAULT false NOT NULL, saldo_terpotong integer DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS public.permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, label text NOT NULL, kategori text DEFAULT 'general' NOT NULL, description text, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.permohonan_berkas (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), permohonan_id uuid NOT NULL, storage_path text NOT NULL, jenis text, nama_file text, size_bytes bigint, uploaded_by uuid, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.rate_limit_hits (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), scope text NOT NULL, subject text NOT NULL, window_start timestamptz NOT NULL, count integer DEFAULT 1 NOT NULL, last_hit_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.rbac_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid, target_user_id uuid, action text NOT NULL, details jsonb DEFAULT '{}' NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.retention_policies (entity text PRIMARY KEY, retention_days integer DEFAULT 365 NOT NULL, enabled boolean DEFAULT true NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, updated_by uuid, last_run_at timestamptz, last_deleted_count integer DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS public.retry_queue (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_name text NOT NULL, payload jsonb DEFAULT '{}', status text DEFAULT 'pending' NOT NULL, attempts integer DEFAULT 0 NOT NULL, last_attempt_at timestamptz, next_attempt_at timestamptz, error text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, max_attempts integer DEFAULT 5 NOT NULL, next_run_at timestamptz, last_error text, request_id text, locked_at timestamptz, locked_by text, completed_at timestamptz);
CREATE TABLE IF NOT EXISTS public.signed_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), document_id uuid NOT NULL, document_hash text NOT NULL, verification_token text NOT NULL, signed_by uuid NOT NULL, signed_at timestamptz DEFAULT now() NOT NULL, status text DEFAULT 'signed' NOT NULL, signed_file_path text NOT NULL, verification_count integer DEFAULT 0 NOT NULL, revoked_at timestamptz, revoke_reason text, created_at timestamptz DEFAULT now() NOT NULL, expires_at timestamptz);
CREATE TABLE IF NOT EXISTS public.signing_certificates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, nip text, full_name text NOT NULL, position text, issued_at timestamptz DEFAULT now() NOT NULL, expired_at timestamptz, public_key text, is_active boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.submission_dispositions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), permohonan_id uuid NOT NULL, from_user uuid NOT NULL, to_user uuid NOT NULL, level text NOT NULL, note text, status text DEFAULT 'pending' NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, acted_at timestamptz);
CREATE TABLE IF NOT EXISTS public.submission_sla_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), permohonan_id uuid NOT NULL, event_type text NOT NULL, started_at timestamptz DEFAULT now() NOT NULL, ended_at timestamptz, duration_seconds integer, reason text, actor uuid, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.uat_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), scenario_id uuid NOT NULL, status text NOT NULL, catatan text, run_at timestamptz DEFAULT now() NOT NULL, run_by uuid, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.uat_scenarios (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), role text NOT NULL, modul text NOT NULL, description text NOT NULL, steps text[] DEFAULT '{}', enabled boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, code text, judul text, expected text);
CREATE TABLE IF NOT EXISTS public.user_permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, permission_code text NOT NULL, granted boolean DEFAULT true NOT NULL, expires_at timestamptz, reason text, granted_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, revoked_at timestamptz);
CREATE TABLE IF NOT EXISTS public.verification_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), target_type text NOT NULL, target_id uuid NOT NULL, actor_id uuid, action text NOT NULL, catatan text, meta jsonb DEFAULT '{}', created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.work_schedule (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nama text NOT NULL, opd_id uuid, hari_kerja integer[] DEFAULT '{1,2,3,4,5}' NOT NULL, jam_masuk time NOT NULL, jam_pulang time NOT NULL, toleransi_menit integer DEFAULT 15 NOT NULL, aktif boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.work_schedule_assignment (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, schedule_id uuid NOT NULL, berlaku_dari date DEFAULT CURRENT_DATE NOT NULL, berlaku_sampai date, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.generated_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), template_id uuid, source_module text, source_ref_id uuid, file_path text NOT NULL, status text DEFAULT 'draft' NOT NULL, opd_id uuid, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, metadata jsonb DEFAULT '{}');
CREATE TABLE IF NOT EXISTS public.signature_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), document_id uuid, signer_id uuid, status text DEFAULT 'pending' NOT NULL, provider text DEFAULT 'mock' NOT NULL, opd_id uuid, payload jsonb DEFAULT '{}', requested_at timestamptz DEFAULT now() NOT NULL, completed_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.signature_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), request_id uuid, event text NOT NULL, payload jsonb DEFAULT '{}', created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.signature_providers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, name text NOT NULL, status text DEFAULT 'inactive' NOT NULL, config jsonb DEFAULT '{}', created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.submission_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid, assignee_id uuid, status text DEFAULT 'pending' NOT NULL, due_at timestamptz, completed_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, task_id uuid, opd_id uuid, payload jsonb DEFAULT '{}');
CREATE TABLE IF NOT EXISTS public.submission_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid, assignee_id uuid, assigned_by uuid, status text DEFAULT 'pending' NOT NULL, task_id uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.submission_delegations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid, from_user uuid, to_user uuid, status text DEFAULT 'pending' NOT NULL, reason text, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.workflow_audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id uuid, submission_id uuid, action text NOT NULL, actor uuid, payload jsonb DEFAULT '{}', created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.workflow_instances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id uuid, submission_id uuid, current_node text, status text DEFAULT 'running' NOT NULL, context jsonb DEFAULT '{}', created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.workflows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nama text NOT NULL, opd_id uuid, definition jsonb DEFAULT '{}' NOT NULL, status text DEFAULT 'draft' NOT NULL, version integer DEFAULT 1 NOT NULL, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);

DO $$ DECLARE r record; BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname='public' LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', r.tablename);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', r.tablename);
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', r.tablename);
  END LOOP;
END $$;

DO $$ DECLARE r record; BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename IN (
    'aset_bast','aset_bast_items','aset_mutasi','aset_opname','aset_opname_items','aset_pemeliharaan','aset_penyusutan_history','aset_verification_campaign','aset_verification_item',
    'attendance_shift_assignment','attendance_shifts','compliance_checklist','consent_log','cron_history','dataset_submission','dataset_submission_review','dataset_template',
    'dead_letter_jobs','digital_signatures','document_audit','documents','dokumen_verifikasi','escalation_config','feature_flags','form_assignments','form_fields',
    'form_submission_comment','form_submission_files','form_submission_versions','form_submissions','form_targets','forms','geofence_audit','hari_libur','ikm_responses','ikm_surveys',
    'leave_balances','lokasi_gedung','lokasi_lantai','lokasi_ruangan','nomor_surat_issued','nomor_surat_sequence','notifications','overtime_requests','payroll_periods',
    'pengajuan_izin','permissions','permohonan_berkas','rate_limit_hits','rbac_audit','retention_policies','retry_queue','signed_documents','signing_certificates',
    'submission_dispositions','submission_sla_events','uat_results','uat_scenarios','user_permissions','verification_logs','work_schedule','work_schedule_assignment',
    'generated_documents','signature_requests','signature_events','signature_providers','submission_tasks','submission_assignments','submission_delegations',
    'workflow_audit_logs','workflow_instances','workflows'
  ) LOOP
    EXECUTE format('DROP POLICY IF EXISTS "admin_all_%s" ON public.%I', r.tablename, r.tablename);
    EXECUTE format('CREATE POLICY "admin_all_%s" ON public.%I FOR ALL TO authenticated USING (public.has_role(auth.uid(),''super_admin''::app_role) OR public.has_role(auth.uid(),''admin_opd''::app_role)) WITH CHECK (public.has_role(auth.uid(),''super_admin''::app_role) OR public.has_role(auth.uid(),''admin_opd''::app_role))', r.tablename, r.tablename);
  END LOOP;
END $$;