-- Base tables (with inline PK for referenced ones)
CREATE TABLE IF NOT EXISTS public.compliance_checklist (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), domain text NOT NULL, kode text NOT NULL, label text NOT NULL, status text DEFAULT 'todo' NOT NULL, bukti_url text, catatan text, updated_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, judul text, deskripsi text);
CREATE TABLE IF NOT EXISTS public.consent_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, consent_type text NOT NULL, version text DEFAULT 'v1' NOT NULL, granted boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.cron_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_name text NOT NULL, status text DEFAULT 'running' NOT NULL, request_id text, started_at timestamptz DEFAULT now() NOT NULL, finished_at timestamptz, duration_ms integer, affected_rows integer, error text, meta jsonb DEFAULT '{}'::jsonb, created_at timestamptz DEFAULT now() NOT NULL, detail jsonb);
CREATE TABLE IF NOT EXISTS public.dataset_submission (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), template_id uuid, user_id uuid NOT NULL, opd_id uuid, data jsonb DEFAULT '{}'::jsonb NOT NULL, status text DEFAULT 'draft' NOT NULL, catatan_review text, reviewed_by uuid, reviewed_at timestamptz, submitted_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, oleh_user_id uuid, review_status text DEFAULT 'pending' NOT NULL, review_note text);
CREATE TABLE IF NOT EXISTS public.dataset_submission_review (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL, reviewer_id uuid NOT NULL, action text NOT NULL, catatan text, created_at timestamptz DEFAULT now() NOT NULL, aksi text);
CREATE TABLE IF NOT EXISTS public.dataset_template (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), judul text NOT NULL, deskripsi text, target_role text DEFAULT 'asn' NOT NULL, target_scope text DEFAULT 'opd_sendiri' NOT NULL, target_opd_ids uuid[] DEFAULT '{}'::uuid[], kolom jsonb DEFAULT '[]'::jsonb NOT NULL, deadline timestamptz, aktif boolean DEFAULT true NOT NULL, allow_multiple_submit boolean DEFAULT false NOT NULL, excel_layout jsonb DEFAULT '{}'::jsonb, created_by uuid, opd_id uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, kode text, opd_pemilik_id uuid);
CREATE TABLE IF NOT EXISTS public.dead_letter_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_name text NOT NULL, payload jsonb DEFAULT '{}'::jsonb, error_message text, retry_count integer DEFAULT 0 NOT NULL, resolved_at timestamptz, resolved_by uuid, request_id text, created_at timestamptz DEFAULT now() NOT NULL, failed_at timestamptz DEFAULT now() NOT NULL, replayed_to uuid, resolution_note text);
CREATE TABLE IF NOT EXISTS public.desa (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nama text NOT NULL, kecamatan text, aktif boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.digital_signatures (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, signature_path text NOT NULL, is_active boolean DEFAULT true NOT NULL, revoked_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, document_type text NOT NULL, generated_by_system boolean DEFAULT false NOT NULL, source_module text, source_ref_id uuid, file_path text NOT NULL, opd_id uuid, created_by uuid NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.document_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), document_id uuid NOT NULL, action text NOT NULL, actor uuid, metadata jsonb DEFAULT '{}'::jsonb NOT NULL, ip_hash text, user_agent text, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.dokumen_verifikasi (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), permohonan_id uuid, storage_path text NOT NULL, jenis text, hash text, size_bytes bigint, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, token text, nomor_surat text, sha256 text, signature_provider text, diterbitkan_oleh uuid);
CREATE TABLE IF NOT EXISTS public.escalation_config (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, layanan_id uuid, threshold_hours integer DEFAULT 48 NOT NULL, action text DEFAULT 'notify' NOT NULL, target_user_id uuid, aktif boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, level integer DEFAULT 1 NOT NULL, threshold_days integer DEFAULT 2 NOT NULL, target_role text DEFAULT 'admin_opd' NOT NULL);
CREATE TABLE IF NOT EXISTS public.feature_flags (key text PRIMARY KEY, enabled boolean DEFAULT true NOT NULL, description text, updated_by uuid, updated_at timestamptz DEFAULT now() NOT NULL, flag_key text);
CREATE TABLE IF NOT EXISTS public.forms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), judul text NOT NULL, deskripsi text, opd_pemilik_id uuid, status text DEFAULT 'draft' NOT NULL, schema_snapshot jsonb DEFAULT '{}'::jsonb, slug text, is_public boolean DEFAULT false NOT NULL, published_at timestamptz, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, deadline timestamptz, allow_multiple_submit boolean DEFAULT false NOT NULL, published_by uuid, archived_at timestamptz);
CREATE TABLE IF NOT EXISTS public.form_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid NOT NULL, user_id uuid, opd_id uuid, status text DEFAULT 'pending' NOT NULL, assigned_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, version_number integer DEFAULT 1 NOT NULL, due_at timestamptz, assigned_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.form_fields (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid NOT NULL, kode text NOT NULL, label text NOT NULL, tipe text DEFAULT 'text' NOT NULL, urutan integer DEFAULT 0 NOT NULL, required boolean DEFAULT false NOT NULL, options jsonb DEFAULT '[]'::jsonb, help text, created_at timestamptz DEFAULT now() NOT NULL, visible_if jsonb, placeholder text, help_text text, validation jsonb DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS public.form_submissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid NOT NULL, user_id uuid, opd_id uuid, data jsonb DEFAULT '{}'::jsonb NOT NULL, status text DEFAULT 'draft' NOT NULL, assignment_id uuid, submitted_at timestamptz, reviewed_at timestamptz, reviewed_by uuid, version_number integer DEFAULT 1 NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, schema_version_snapshot jsonb, review_note text);
CREATE TABLE IF NOT EXISTS public.form_submission_comment (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL, oleh uuid, pesan text NOT NULL, internal_only boolean DEFAULT false NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.form_submission_files (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL, field_kode text, storage_path text NOT NULL, provider text DEFAULT 'supabase' NOT NULL, mime text, size_bytes bigint, cleanup_status text DEFAULT 'ok', created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, uploaded_by uuid, finalized_at timestamptz);
CREATE TABLE IF NOT EXISTS public.form_submission_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL, version integer DEFAULT 1 NOT NULL, data jsonb DEFAULT '{}'::jsonb NOT NULL, files jsonb DEFAULT '[]'::jsonb, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.form_targets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid NOT NULL, target_type text NOT NULL, target_id uuid, created_at timestamptz DEFAULT now() NOT NULL, target_value text);
CREATE TABLE IF NOT EXISTS public.geofence_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid, opd_id uuid, lat numeric, lng numeric, dist_m numeric, radius_m numeric, valid boolean, reason text, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.hari_libur (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tanggal date NOT NULL, nama text NOT NULL, jenis text DEFAULT 'nasional' NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, nasional boolean DEFAULT true NOT NULL, catatan text);
CREATE TABLE IF NOT EXISTS public.ikm_responses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), survey_id uuid NOT NULL, permohonan_id uuid, user_id uuid, u1 integer, u2 integer, u3 integer, u4 integer, u5 integer, u6 integer, u7 integer, u8 integer, u9 integer, saran text, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.ikm_surveys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, layanan_id uuid, judul text NOT NULL, aktif boolean DEFAULT true NOT NULL, mulai date, selesai date, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, periode text, created_by uuid);
CREATE TABLE IF NOT EXISTS public.leave_balances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, tahun integer NOT NULL, jenis text NOT NULL, kuota integer DEFAULT 0 NOT NULL, terpakai integer DEFAULT 0 NOT NULL, catatan text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.lokasi_gedung (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nama text NOT NULL, alamat text, opd_id uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.lokasi_lantai (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), gedung_id uuid NOT NULL, nama text NOT NULL, urutan integer DEFAULT 0 NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.lokasi_ruangan (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lantai_id uuid NOT NULL, nama text NOT NULL, kode text, pic_user_id uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.nomor_surat_issued (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nomor text NOT NULL, tahun integer NOT NULL, opd_id uuid, permohonan_id uuid, issued_at timestamptz DEFAULT now() NOT NULL, issued_by uuid, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.nomor_surat_sequence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, tahun integer NOT NULL, last_number integer DEFAULT 0 NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, tipe text NOT NULL, judul text NOT NULL, body text, link text, meta jsonb DEFAULT '{}'::jsonb, dibaca boolean DEFAULT false NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.overtime_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, opd_id uuid, tanggal date NOT NULL, jam_mulai time NOT NULL, jam_selesai time NOT NULL, alasan text, status text DEFAULT 'pending' NOT NULL, approved_by uuid, catatan_approval text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, approved_at timestamptz);
CREATE TABLE IF NOT EXISTS public.payroll_periods (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, tahun integer NOT NULL, bulan integer NOT NULL, locked_at timestamptz, locked_by uuid, unlocked_at timestamptz, unlocked_by uuid, catatan text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.pengajuan_izin (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, opd_id uuid, jenis text NOT NULL, dari date NOT NULL, sampai date NOT NULL, alasan text, lampiran_url text, status text DEFAULT 'pending' NOT NULL, approved_by uuid, catatan_approval text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, approved_at timestamptz, mengurangi_saldo boolean DEFAULT false NOT NULL, saldo_terpotong integer DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS public.permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL, label text NOT NULL, kategori text DEFAULT 'general' NOT NULL, description text, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.permohonan_berkas (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), permohonan_id uuid NOT NULL, storage_path text NOT NULL, jenis text, nama_file text, size_bytes bigint, uploaded_by uuid, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.master_jabatan (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kode text UNIQUE NOT NULL, nama text NOT NULL, kategori text, urutan integer NOT NULL DEFAULT 0, aktif boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.form_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid NOT NULL REFERENCES public.forms(id) ON DELETE CASCADE, version_number integer NOT NULL, fields jsonb NOT NULL DEFAULT '[]'::jsonb, meta jsonb NOT NULL DEFAULT '{}'::jsonb, published_at timestamptz, published_by uuid, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid, UNIQUE (form_id, version_number));
CREATE TABLE IF NOT EXISTS public.form_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, code text UNIQUE, description text, category text, scope text NOT NULL DEFAULT 'opd', owner_opd_id uuid REFERENCES public.opd(id), allowed_employee_types text[] NOT NULL DEFAULT ARRAY[]::text[], fields jsonb NOT NULL DEFAULT '[]'::jsonb, workflow jsonb, status text NOT NULL DEFAULT 'draft', created_by uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS public.workflow_definitions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid NOT NULL REFERENCES public.forms(id) ON DELETE CASCADE, name text NOT NULL, description text, current_version_id uuid, created_by uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS public.workflow_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id uuid NOT NULL REFERENCES public.workflow_definitions(id) ON DELETE CASCADE, version_number integer NOT NULL, status text NOT NULL DEFAULT 'draft', locked boolean NOT NULL DEFAULT false, submission_count integer NOT NULL DEFAULT 0, graph jsonb NOT NULL DEFAULT '{"nodes":[],"edges":[]}'::jsonb, published_at timestamptz, published_by uuid, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid, UNIQUE (workflow_id, version_number));
CREATE TABLE IF NOT EXISTS public.workflow_nodes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_version_id uuid NOT NULL REFERENCES public.workflow_versions(id) ON DELETE CASCADE, node_key text NOT NULL, node_type text NOT NULL, label text, config jsonb NOT NULL DEFAULT '{}'::jsonb, sla_hours integer, position jsonb, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (workflow_version_id, node_key));
CREATE TABLE IF NOT EXISTS public.workflow_edges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_version_id uuid NOT NULL REFERENCES public.workflow_versions(id) ON DELETE CASCADE, from_node text NOT NULL, to_node text NOT NULL, condition jsonb, label text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.submission_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL REFERENCES public.form_submissions(id) ON DELETE CASCADE, version_number integer NOT NULL, values jsonb NOT NULL DEFAULT '{}'::jsonb, reason text, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid, UNIQUE (submission_id, version_number));
CREATE TABLE IF NOT EXISTS public.submission_values (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL REFERENCES public.form_submissions(id) ON DELETE CASCADE, version_id uuid REFERENCES public.submission_versions(id) ON DELETE CASCADE, field_kode text NOT NULL, value jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.submission_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL REFERENCES public.form_submissions(id) ON DELETE CASCADE, workflow_version_id uuid REFERENCES public.workflow_versions(id), node_key text NOT NULL, node_type text NOT NULL, status text NOT NULL DEFAULT 'pending', due_at timestamptz, sla_hours integer, completed_at timestamptz, result jsonb, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.submission_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task_id uuid NOT NULL REFERENCES public.submission_tasks(id) ON DELETE CASCADE, assignee_id uuid NOT NULL, assigned_by uuid, assigned_at timestamptz NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'active', UNIQUE (task_id, assignee_id));
CREATE TABLE IF NOT EXISTS public.submission_delegations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task_id uuid NOT NULL REFERENCES public.submission_tasks(id) ON DELETE CASCADE, from_user_id uuid NOT NULL, to_user_id uuid NOT NULL, reason text, delegated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.submission_escalations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task_id uuid NOT NULL REFERENCES public.submission_tasks(id) ON DELETE CASCADE, level integer NOT NULL DEFAULT 1, reason text, escalated_to uuid, escalated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.submission_sequences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), scope text NOT NULL, tahun integer NOT NULL, last_number integer NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (scope, tahun));
CREATE TABLE IF NOT EXISTS public.document_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid REFERENCES public.forms(id) ON DELETE CASCADE, owner_opd_id uuid REFERENCES public.opd(id), name text NOT NULL, description text, template_html text, template_storage_path text, variables jsonb NOT NULL DEFAULT '[]'::jsonb, status text NOT NULL DEFAULT 'draft', created_by uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS public.generated_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL REFERENCES public.form_submissions(id) ON DELETE CASCADE, template_id uuid REFERENCES public.document_templates(id), storage_path text NOT NULL, mime text NOT NULL DEFAULT 'application/pdf', size_bytes bigint, signed_document_id uuid REFERENCES public.signed_documents(id), generated_at timestamptz NOT NULL DEFAULT now(), generated_by uuid);
CREATE TABLE IF NOT EXISTS public.form_audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid, action text NOT NULL, resource_type text NOT NULL, resource_id uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, ip_address inet, user_agent text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.workflow_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, code text, description text, category text, scope text NOT NULL DEFAULT 'opd', owner_opd_id uuid REFERENCES public.opd(id) ON DELETE SET NULL, status text NOT NULL DEFAULT 'draft', graph jsonb NOT NULL DEFAULT '{"nodes":[],"edges":[]}'::jsonb, created_by uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.workflow_audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid, action text NOT NULL, resource_type text NOT NULL, resource_id uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.document_template_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), template_id uuid NOT NULL REFERENCES public.document_templates(id) ON DELETE CASCADE, version_number int NOT NULL, kind text NOT NULL, template_html text, template_storage_path text, variables jsonb NOT NULL DEFAULT '{}'::jsonb, created_by uuid, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(template_id, version_number));
CREATE TABLE IF NOT EXISTS public.document_numbering_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, name text NOT NULL, format text NOT NULL, scope text NOT NULL DEFAULT 'global', category text, opd_id uuid REFERENCES public.opd(id) ON DELETE SET NULL, reset_period text NOT NULL DEFAULT 'yearly', padding int NOT NULL DEFAULT 6, status text NOT NULL DEFAULT 'active', created_by uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.document_numbering_sequences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rule_id uuid NOT NULL REFERENCES public.document_numbering_rules(id) ON DELETE CASCADE, scope_key text NOT NULL DEFAULT '', year int NOT NULL, last_number int NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(rule_id, scope_key, year));
CREATE TABLE IF NOT EXISTS public.document_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), document_id uuid NOT NULL REFERENCES public.generated_documents(id) ON DELETE CASCADE, action text NOT NULL, actor_id uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.signature_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), document_id uuid, signer_id uuid, status text DEFAULT 'pending' NOT NULL, provider text DEFAULT 'mock' NOT NULL, opd_id uuid, payload jsonb DEFAULT '{}'::jsonb, requested_at timestamptz DEFAULT now() NOT NULL, completed_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.signature_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), request_id uuid, event text NOT NULL, payload jsonb DEFAULT '{}'::jsonb, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.signature_providers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, name text NOT NULL, status text DEFAULT 'inactive' NOT NULL, config jsonb DEFAULT '{}'::jsonb, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.workflow_instances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id uuid, submission_id uuid, current_node text, status text DEFAULT 'running' NOT NULL, context jsonb DEFAULT '{}'::jsonb, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.workflows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nama text NOT NULL, opd_id uuid, definition jsonb DEFAULT '{}'::jsonb NOT NULL, status text DEFAULT 'draft' NOT NULL, version integer DEFAULT 1 NOT NULL, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.branding (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text UNIQUE NOT NULL, value jsonb DEFAULT '{}'::jsonb NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, updated_by uuid);
CREATE TABLE IF NOT EXISTS public.aset_nilai_buku (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), aset_id uuid NOT NULL, periode text NOT NULL, nilai_perolehan numeric DEFAULT 0, akumulasi_penyusutan numeric DEFAULT 0, nilai_buku numeric DEFAULT 0, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.form_wizard_drafts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, form_id uuid, step text, payload jsonb DEFAULT '{}'::jsonb NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.signature_request_signers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), request_id uuid NOT NULL, user_id uuid, role text, status text DEFAULT 'pending' NOT NULL, signed_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.notification_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, channel text NOT NULL, key text NOT NULL, subject text, body text NOT NULL, variables jsonb NOT NULL DEFAULT '[]'::jsonb, enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, UNIQUE (opd_id, channel, key));

-- Grants + RLS + admin policies
DO $g$ DECLARE t text; tables text[] := ARRAY['compliance_checklist','consent_log','cron_history','dataset_submission','dataset_submission_review','dataset_template','dead_letter_jobs','desa','digital_signatures','document_audit','documents','dokumen_verifikasi','escalation_config','feature_flags','form_assignments','form_fields','form_submission_comment','form_submission_files','form_submission_versions','form_submissions','form_targets','forms','geofence_audit','hari_libur','ikm_responses','ikm_surveys','leave_balances','lokasi_gedung','lokasi_lantai','lokasi_ruangan','nomor_surat_issued','nomor_surat_sequence','notifications','overtime_requests','payroll_periods','pengajuan_izin','permissions','permohonan_berkas','master_jabatan','form_versions','form_templates','workflow_definitions','workflow_versions','workflow_nodes','workflow_edges','submission_versions','submission_values','submission_tasks','submission_assignments','submission_delegations','submission_escalations','submission_sequences','document_templates','generated_documents','form_audit_logs','workflow_templates','workflow_audit_logs','document_template_versions','document_numbering_rules','document_numbering_sequences','document_history','signature_requests','signature_events','signature_providers','workflow_instances','workflows','branding','aset_nilai_buku','form_wizard_drafts','signature_request_signers','notification_templates'];
BEGIN FOREACH t IN ARRAY tables LOOP
  BEGIN
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', t);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS "auth_admin_all_%s" ON public.%I', t, t);
    EXECUTE format('CREATE POLICY "auth_admin_all_%s" ON public.%I TO authenticated USING (public.has_role(auth.uid(),''super_admin'') OR public.has_role(auth.uid(),''admin_opd'')) WITH CHECK (public.has_role(auth.uid(),''super_admin''))', t, t);
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END LOOP; END $g$;

DO $g$ DECLARE t text; readable text[] := ARRAY['desa','hari_libur','forms','form_fields','form_templates','workflow_templates','master_jabatan','permissions','feature_flags','document_templates','signature_providers'];
BEGIN FOREACH t IN ARRAY readable LOOP
  BEGIN
    EXECUTE format('DROP POLICY IF EXISTS "auth_read_%s" ON public.%I', t, t);
    EXECUTE format('CREATE POLICY "auth_read_%s" ON public.%I FOR SELECT TO authenticated USING (true)', t, t);
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END LOOP; END $g$;

DROP POLICY IF EXISTS "notifications_self" ON public.notifications;
CREATE POLICY "notifications_self" ON public.notifications FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());