ALTER TABLE public.forms ADD COLUMN IF NOT EXISTS show_in_open_data boolean NOT NULL DEFAULT false;
ALTER TABLE public.laporan_masyarakat ADD COLUMN IF NOT EXISTS ticket_code text, ADD COLUMN IF NOT EXISTS pelapor_id uuid;

DO $$ BEGIN ALTER TABLE public.forms ADD CONSTRAINT forms_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; WHEN invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.form_submissions ADD CONSTRAINT form_submissions_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; WHEN invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.generated_documents ADD CONSTRAINT generated_documents_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; WHEN invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.document_templates ADD CONSTRAINT document_templates_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; WHEN invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.signature_requests ADD CONSTRAINT signature_requests_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; WHEN invalid_table_definition THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.form_submissions ADD CONSTRAINT form_submissions_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN invalid_table_definition THEN NULL; WHEN foreign_key_violation THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.generated_documents ADD CONSTRAINT generated_documents_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.form_submissions(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN invalid_table_definition THEN NULL; WHEN foreign_key_violation THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.generated_documents ADD CONSTRAINT generated_documents_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.document_templates(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN invalid_table_definition THEN NULL; WHEN foreign_key_violation THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.signature_requests ADD CONSTRAINT signature_requests_generated_document_id_fkey FOREIGN KEY (generated_document_id) REFERENCES public.generated_documents(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN invalid_table_definition THEN NULL; WHEN foreign_key_violation THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.signature_request_signers ADD CONSTRAINT signature_request_signers_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.signature_requests(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN invalid_table_definition THEN NULL; WHEN foreign_key_violation THEN NULL; END $$;

DROP FUNCTION IF EXISTS public.fn_approve_user(uuid, public.app_role, text);
CREATE OR REPLACE FUNCTION public.fn_approve_user(_target_user_id uuid, _role public.app_role, _method text DEFAULT 'manual') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN UPDATE public.profiles SET verification_status='verified', verified_at=now(), verified_by=auth.uid(), requested_role=COALESCE(_role, requested_role), verification_method=_method WHERE id=_target_user_id; INSERT INTO public.user_roles(user_id, role) VALUES (_target_user_id, _role) ON CONFLICT DO NOTHING; RETURN jsonb_build_object('ok', true); END $$;
GRANT EXECUTE ON FUNCTION public.fn_approve_user(uuid, public.app_role, text) TO authenticated, service_role;
DROP FUNCTION IF EXISTS public.fn_reject_user(uuid, text);
CREATE OR REPLACE FUNCTION public.fn_reject_user(_target_user_id uuid, _reason text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN UPDATE public.profiles SET verification_status='rejected', rejected_at=now(), rejected_by=auth.uid(), rejection_reason=_reason WHERE id=_target_user_id; RETURN jsonb_build_object('ok', true); END $$;
GRANT EXECUTE ON FUNCTION public.fn_reject_user(uuid, text) TO authenticated, service_role;

DROP FUNCTION IF EXISTS public.opd_kinerja_trend(uuid, integer);
CREATE OR REPLACE FUNCTION public.opd_kinerja_trend(_opd uuid DEFAULT NULL, _months integer DEFAULT 12) RETURNS TABLE(bulan text, masuk bigint, selesai bigint, on_time bigint, selesai_dengan_sla bigint) LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT to_char(date_trunc('month', tanggal_masuk),'YYYY-MM') AS bulan, count(*) AS masuk, count(*) FILTER (WHERE status='selesai') AS selesai, count(*) FILTER (WHERE status='selesai' AND (tenggat IS NULL OR updated_at <= tenggat)) AS on_time, count(*) FILTER (WHERE status='selesai' AND tenggat IS NOT NULL) AS selesai_dengan_sla FROM public.permohonan WHERE (_opd IS NULL OR opd_id=_opd) AND tanggal_masuk >= date_trunc('month', now()) - make_interval(months => COALESCE(_months,12)) GROUP BY 1 ORDER BY 1 $$;
GRANT EXECUTE ON FUNCTION public.opd_kinerja_trend(uuid,integer) TO authenticated, service_role;
DROP FUNCTION IF EXISTS public.layanan_kinerja_agg();
CREATE OR REPLACE FUNCTION public.layanan_kinerja_agg() RETURNS TABLE(layanan_id uuid, layanan_judul text, opd_id uuid, opd_singkatan text, kategori text, total bigint, selesai bigint, on_time bigint, selesai_dengan_sla bigint, rata_hari_selesai numeric) LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT lp.id, COALESCE(lp.judul,p.kategori), p.opd_id, o.singkatan, p.kategori, count(p.id), count(p.id) FILTER (WHERE p.status='selesai'), count(p.id) FILTER (WHERE p.status='selesai' AND (p.tenggat IS NULL OR p.updated_at <= p.tenggat)), count(p.id) FILTER (WHERE p.status='selesai' AND p.tenggat IS NOT NULL), COALESCE(avg(EXTRACT(EPOCH FROM (p.updated_at - p.tanggal_masuk))/86400.0) FILTER (WHERE p.status='selesai'),0)::numeric FROM public.permohonan p LEFT JOIN public.layanan_publik lp ON lp.judul = p.kategori OR lp.slug = p.kategori LEFT JOIN public.opd o ON o.id=p.opd_id GROUP BY lp.id, lp.judul, p.opd_id, o.singkatan, p.kategori $$;
GRANT EXECUTE ON FUNCTION public.layanan_kinerja_agg() TO authenticated, service_role;
DROP FUNCTION IF EXISTS public.opd_skor_komposit();
CREATE OR REPLACE FUNCTION public.opd_skor_komposit() RETURNS TABLE(opd_id uuid, opd_nama text, opd_singkatan text, kategori text[], total bigint, selesai bigint, sla_pct numeric, rating_avg numeric, completion_pct numeric, skor numeric) LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT o.id, o.nama, o.singkatan, o.kategori, count(p.id), count(p.id) FILTER (WHERE p.status='selesai'), CASE WHEN count(p.id) FILTER (WHERE p.status='selesai') > 0 THEN round(100.0 * count(p.id) FILTER (WHERE p.status='selesai' AND (p.tenggat IS NULL OR p.updated_at <= p.tenggat)) / count(p.id) FILTER (WHERE p.status='selesai'), 2) ELSE NULL END, COALESCE(avg(r.skor),0)::numeric, CASE WHEN count(p.id) > 0 THEN round(100.0 * count(p.id) FILTER (WHERE p.status='selesai') / count(p.id),2) ELSE NULL END, LEAST(100, COALESCE(round(100.0 * count(p.id) FILTER (WHERE p.status='selesai') / NULLIF(count(p.id),0),2),0)) FROM public.opd o LEFT JOIN public.permohonan p ON p.opd_id=o.id LEFT JOIN public.permohonan_rating r ON r.permohonan_id=p.id GROUP BY o.id,o.nama,o.singkatan,o.kategori $$;
GRANT EXECUTE ON FUNCTION public.opd_skor_komposit() TO authenticated, service_role;
DROP FUNCTION IF EXISTS public.opd_kategori_benchmark(text);
CREATE OR REPLACE FUNCTION public.opd_kategori_benchmark(_kategori text) RETURNS TABLE(opd_id uuid, opd_nama text, opd_singkatan text, total bigint, selesai bigint, skor numeric) LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT o.id,o.nama,o.singkatan,count(p.id),count(p.id) FILTER (WHERE p.status='selesai'),LEAST(100,count(p.id)::numeric) FROM public.opd o LEFT JOIN public.permohonan p ON p.opd_id=o.id AND p.kategori=_kategori GROUP BY o.id,o.nama,o.singkatan $$;
GRANT EXECUTE ON FUNCTION public.opd_kategori_benchmark(text) TO authenticated, service_role;