-- Baseline catch-up migration generated by introspection
-- Idempotent: safe to run multiple times
-- Source: live database (public schema)

SET search_path = public;

-- =====================  ENUMS  =====================
DO $$ BEGIN
  CREATE TYPE public.app_role AS ENUM ('warga', 'admin_opd', 'super_admin', 'admin_desa', 'asn', 'admin_pemda', 'pimpinan');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.bast_status AS ENUM ('draft', 'issued', 'approved', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.checklist_status AS ENUM ('todo', 'in_progress', 'done', 'na');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.izin_jenis AS ENUM ('cuti_tahunan', 'cuti_sakit', 'dinas_luar', 'wfh', 'lainnya');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.izin_status AS ENUM ('pending', 'approved', 'rejected', 'dibatalkan');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.job_status AS ENUM ('pending', 'running', 'success', 'failed', 'dead');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.metode_susut AS ENUM ('garis_lurus', 'saldo_menurun');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.mutasi_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.retry_status AS ENUM ('pending', 'retrying', 'success', 'dead_letter', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.shift_jenis AS ENUM ('pagi', 'malam', 'khusus');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.sla_event_type AS ENUM ('pause', 'resume', 'reset');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.status_permohonan AS ENUM ('baru', 'diproses', 'selesai', 'ditolak', 'menunggu_dokumen');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.submission_status AS ENUM ('draft', 'submitted', 'approved', 'rejected', 'revision');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE public.uat_result_status AS ENUM ('pass', 'partial', 'fail');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.absensi_asn (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "opd_id" uuid,
  "tipe" text NOT NULL,
  "waktu" timestamp with time zone DEFAULT now() NOT NULL,
  "lokasi" text, "lat" numeric, "lng" numeric,
  "foto_url" text, "catatan" text, "device_info" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "device_fingerprint_hash" text,
  "is_late" boolean DEFAULT false NOT NULL,
  "late_minutes" integer DEFAULT 0 NOT NULL,
  "schedule_id" uuid
);
CREATE TABLE IF NOT EXISTS public.app_setting (
  "key" text NOT NULL,
  "value" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "category" text DEFAULT 'internal'::text NOT NULL,
  "public_visible" boolean DEFAULT false NOT NULL
);
CREATE TABLE IF NOT EXISTS public.aset (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "kode" text NOT NULL, "nama" text NOT NULL, "kategori" text,
  "kondisi" text DEFAULT 'baik'::text NOT NULL, "lokasi" text,
  "opd_id" uuid, "pemegang_user_id" uuid,
  "nilai_perolehan" numeric DEFAULT 0,
  "tanggal_perolehan" date, "deskripsi" text, "foto_url" text,
  "merk" text, "nomor_seri" text, "lokasi_terkini" text, "lat" numeric, "lng" numeric,
  "status" text DEFAULT 'aktif'::text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "catatan" text, "kib" text,
  "version_number" integer DEFAULT 1 NOT NULL,
  "qr_token" text, "lifecycle_status" text DEFAULT 'aktif'::text,
  "last_verified_at" timestamp with time zone,
  "garansi_sampai" date, "kalibrasi_berikut" date,
  "umur_ekonomis_bulan" integer, "metode_susut" text,
  "dokumen_kehilangan_url" text, "nilai_sisa" numeric DEFAULT 0
);
CREATE TABLE IF NOT EXISTS public.aset_bast (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "nomor" text NOT NULL, "pemberi_user" uuid, "penerima_user" uuid, "opd_id" uuid,
  "tanggal" date DEFAULT CURRENT_DATE NOT NULL, "catatan" text,
  "status" text DEFAULT 'issued'::text NOT NULL,
  "created_by" uuid, "approved_by" uuid, "approved_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.aset_bast_items (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "bast_id" uuid NOT NULL, "aset_id" uuid NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.aset_mutasi (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "aset_id" uuid NOT NULL, "dari_user" uuid, "ke_user" uuid, "dari_opd" uuid, "ke_opd" uuid,
  "alasan" text, "diajukan_oleh" uuid,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "catatan" text, "ttd_url" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "approved_by" uuid, "approved_at" timestamp with time zone, "catatan_approval" text
);
CREATE TABLE IF NOT EXISTS public.aset_opname (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL, "opd_id" uuid,
  "periode" text NOT NULL,
  "status" text DEFAULT 'open'::text NOT NULL, "catatan" text,
  "dibuat_oleh" uuid, "ditutup_oleh" uuid, "closed_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.aset_opname_items (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "opname_id" uuid NOT NULL, "aset_id" uuid NOT NULL,
  "hadir" boolean, "kondisi_temuan" text, "catatan" text, "verified_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.aset_pemeliharaan (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "aset_id" uuid NOT NULL, "opd_id" uuid,
  "jenis" text, "deskripsi" text, "jadwal" date, "selesai_at" timestamp with time zone,
  "biaya" numeric DEFAULT 0, "vendor" text,
  "status" text DEFAULT 'dijadwalkan'::text NOT NULL, "created_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.aset_penyusutan_history (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "aset_id" uuid NOT NULL, "periode" text NOT NULL,
  "susut_bulan" numeric DEFAULT 0 NOT NULL,
  "akumulasi" numeric DEFAULT 0 NOT NULL,
  "nilai_buku" numeric DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.aset_riwayat (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "aset_id" uuid NOT NULL, "aksi" text NOT NULL, "catatan" text,
  "oleh" uuid, "data" jsonb, "lat" numeric, "lng" numeric, "lokasi_text" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.aset_verification_campaign (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "nama" text NOT NULL, "opd_id" uuid,
  "status" text DEFAULT 'open'::text NOT NULL,
  "catatan" text, "created_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deskripsi" text, "periode_mulai" date, "periode_selesai" date,
  "target_opd_ids" uuid[] DEFAULT '{}'::uuid[] NOT NULL
);
CREATE TABLE IF NOT EXISTS public.aset_verification_item (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "campaign_id" uuid NOT NULL, "aset_id" uuid NOT NULL,
  "verified" boolean DEFAULT false, "kondisi" text, "catatan" text,
  "verified_by" uuid, "verified_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "opd_id" uuid,
  "status" text DEFAULT 'belum'::text NOT NULL,
  "lat" numeric, "lng" numeric, "lokasi_text" text, "foto_url" text
);
CREATE TABLE IF NOT EXISTS public.attendance_shift_assignment (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL, "shift_id" uuid NOT NULL,
  "dari" date NOT NULL, "sampai" date,
  "aktif" boolean DEFAULT true NOT NULL, "created_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.attendance_shifts (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL, "opd_id" uuid,
  "nama" text NOT NULL,
  "jam_masuk" time without time zone NOT NULL,
  "jam_pulang" time without time zone NOT NULL,
  "toleransi_menit" integer DEFAULT 15 NOT NULL,
  "jenis" text DEFAULT 'pagi'::text NOT NULL,
  "aktif" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.audit_log (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid, "user_email" text,
  "aksi" text NOT NULL, "entitas" text NOT NULL, "entitas_id" text,
  "data_sebelum" jsonb, "data_sesudah" jsonb,
  "ip_address" text, "user_agent" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "actor_id" uuid, "correlation_id" text, "request_id" text
);
CREATE TABLE IF NOT EXISTS public.backup_snapshot (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "label" text NOT NULL,
  "tipe" text DEFAULT 'manual'::text NOT NULL,
  "size_bytes" bigint DEFAULT 0 NOT NULL,
  "table_counts" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "data" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_by" uuid
);
CREATE TABLE IF NOT EXISTS public.berita (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "judul" text NOT NULL, "slug" text NOT NULL,
  "ringkasan" text, "isi" text DEFAULT ''::text NOT NULL, "gambar_url" text,
  "status" text DEFAULT 'draft'::text NOT NULL,
  "published_at" timestamp with time zone, "penulis_id" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.compliance_checklist (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "domain" text NOT NULL, "kode" text NOT NULL, "label" text NOT NULL,
  "status" text DEFAULT 'todo'::text NOT NULL,
  "bukti_url" text, "catatan" text, "updated_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "judul" text, "deskripsi" text
);
CREATE TABLE IF NOT EXISTS public.consent_log (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL, "consent_type" text NOT NULL,
  "version" text DEFAULT 'v1'::text NOT NULL,
  "granted" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.cron_history (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "job_name" text NOT NULL,
  "status" text DEFAULT 'running'::text NOT NULL,
  "request_id" text,
  "started_at" timestamp with time zone DEFAULT now() NOT NULL,
  "finished_at" timestamp with time zone,
  "duration_ms" integer, "affected_rows" integer, "error" text,
  "meta" jsonb DEFAULT '{}'::jsonb,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "detail" jsonb
);
CREATE TABLE IF NOT EXISTS public.data_terpadu_item (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "kategori" text NOT NULL, "label" text NOT NULL,
  "nilai_teks" text, "nilai_num" numeric, "nilai_num2" numeric,
  "satuan" text, "trend" text, "ikon" text, "format" text, "ukuran" text, "url" text, "opd" text,
  "aktif" boolean DEFAULT true NOT NULL,
  "urutan" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.dataset_submission (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "template_id" uuid, "user_id" uuid NOT NULL, "opd_id" uuid,
  "data" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "status" text DEFAULT 'draft'::text NOT NULL,
  "catatan_review" text, "reviewed_by" uuid, "reviewed_at" timestamp with time zone,
  "submitted_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "oleh_user_id" uuid,
  "review_status" text DEFAULT 'pending'::text NOT NULL,
  "review_note" text
);
CREATE TABLE IF NOT EXISTS public.dataset_submission_review (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "submission_id" uuid NOT NULL, "reviewer_id" uuid NOT NULL,
  "action" text NOT NULL, "catatan" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "aksi" text
);
CREATE TABLE IF NOT EXISTS public.dataset_template (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "judul" text NOT NULL, "deskripsi" text,
  "target_role" text DEFAULT 'asn'::text NOT NULL,
  "target_scope" text DEFAULT 'opd_sendiri'::text NOT NULL,
  "target_opd_ids" uuid[] DEFAULT '{}'::uuid[],
  "kolom" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "deadline" timestamp with time zone,
  "aktif" boolean DEFAULT true NOT NULL,
  "allow_multiple_submit" boolean DEFAULT false NOT NULL,
  "excel_layout" jsonb DEFAULT '{"group_by": "opd", "sheet_name": "Rangkuman"}'::jsonb,
  "created_by" uuid, "opd_id" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "kode" text, "opd_pemilik_id" uuid
);
CREATE TABLE IF NOT EXISTS public.dead_letter_jobs (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "job_name" text NOT NULL,
  "payload" jsonb DEFAULT '{}'::jsonb,
  "error_message" text,
  "retry_count" integer DEFAULT 0 NOT NULL,
  "resolved_at" timestamp with time zone, "resolved_by" uuid,
  "request_id" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "failed_at" timestamp with time zone DEFAULT now() NOT NULL,
  "replayed_to" uuid, "resolution_note" text
);
CREATE TABLE IF NOT EXISTS public.desa (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "nama" text NOT NULL, "kecamatan" text,
  "aktif" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.digital_signatures (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL, "signature_path" text NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "revoked_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.document_audit (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "document_id" uuid NOT NULL, "action" text NOT NULL, "actor" uuid,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "ip_hash" text, "user_agent" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.documents (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "title" text NOT NULL, "document_type" text NOT NULL,
  "generated_by_system" boolean DEFAULT false NOT NULL,
  "source_module" text, "source_ref_id" uuid,
  "file_path" text NOT NULL,
  "opd_id" uuid, "created_by" uuid NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.dokumen_verifikasi (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "permohonan_id" uuid, "storage_path" text NOT NULL,
  "jenis" text, "hash" text, "size_bytes" bigint, "created_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "token" text, "nomor_surat" text, "sha256" text,
  "signature_provider" text, "diterbitkan_oleh" uuid
);
CREATE TABLE IF NOT EXISTS public.escalation_config (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "opd_id" uuid, "layanan_id" uuid,
  "threshold_hours" integer DEFAULT 48 NOT NULL,
  "action" text DEFAULT 'notify'::text NOT NULL,
  "target_user_id" uuid,
  "aktif" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "level" integer DEFAULT 1 NOT NULL,
  "threshold_days" integer DEFAULT 2 NOT NULL,
  "target_role" text DEFAULT 'admin_opd'::text NOT NULL
);
