CREATE TABLE IF NOT EXISTS public.form_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid NOT NULL, version_number integer NOT NULL, fields jsonb DEFAULT '[]'::jsonb NOT NULL, meta jsonb DEFAULT '{}'::jsonb NOT NULL, published_at timestamptz, published_by uuid, created_at timestamptz DEFAULT now() NOT NULL, created_by uuid, UNIQUE (form_id, version_number));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.form_versions TO authenticated; GRANT ALL ON public.form_versions TO service_role; ALTER TABLE public.form_versions ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.form_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, code text UNIQUE, description text, category text, scope text DEFAULT 'opd' NOT NULL, owner_opd_id uuid, allowed_employee_types public.employment_type[] DEFAULT ARRAY[]::public.employment_type[] NOT NULL, fields jsonb DEFAULT '[]'::jsonb NOT NULL, workflow jsonb, status text DEFAULT 'draft' NOT NULL, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, deleted_at timestamptz);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.form_templates TO authenticated; GRANT ALL ON public.form_templates TO service_role; ALTER TABLE public.form_templates ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.workflow_definitions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid, code text, name text NOT NULL, description text, category text, status text DEFAULT 'draft' NOT NULL, opd_pemilik_id uuid, current_version_id uuid, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, deleted_at timestamptz, archived_at timestamptz);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.workflow_definitions TO authenticated; GRANT ALL ON public.workflow_definitions TO service_role; ALTER TABLE public.workflow_definitions ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.workflow_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id uuid NOT NULL, version_number integer DEFAULT 1 NOT NULL, status text DEFAULT 'draft' NOT NULL, locked boolean DEFAULT false NOT NULL, submission_count integer DEFAULT 0 NOT NULL, graph jsonb DEFAULT '{"nodes":[],"edges":[]}'::jsonb NOT NULL, definition jsonb DEFAULT '{}'::jsonb, published_at timestamptz, published_by uuid, created_at timestamptz DEFAULT now() NOT NULL, created_by uuid, UNIQUE (workflow_id, version_number));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.workflow_versions TO authenticated; GRANT ALL ON public.workflow_versions TO service_role; ALTER TABLE public.workflow_versions ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.workflow_nodes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_version_id uuid, version_id uuid, node_key text, code text, node_type text, type text, label text, config jsonb DEFAULT '{}'::jsonb NOT NULL, sla_hours integer, position jsonb, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.workflow_nodes TO authenticated; GRANT ALL ON public.workflow_nodes TO service_role; ALTER TABLE public.workflow_nodes ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.workflow_edges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_version_id uuid, version_id uuid, from_node text, to_node text, source_node text, target_node text, condition jsonb, label text, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.workflow_edges TO authenticated; GRANT ALL ON public.workflow_edges TO service_role; ALTER TABLE public.workflow_edges ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.submission_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL, version_number integer DEFAULT 1 NOT NULL, values jsonb DEFAULT '{}'::jsonb, data jsonb DEFAULT '{}'::jsonb, reason text, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, UNIQUE (submission_id, version_number));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.submission_versions TO authenticated; GRANT ALL ON public.submission_versions TO service_role; ALTER TABLE public.submission_versions ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.submission_values (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL, version_id uuid, field_kode text NOT NULL, value jsonb, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.submission_values TO authenticated; GRANT ALL ON public.submission_values TO service_role; ALTER TABLE public.submission_values ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.submission_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL, workflow_version_id uuid, node_key text NOT NULL, node_type text NOT NULL, status text DEFAULT 'pending' NOT NULL, due_at timestamptz, sla_hours integer, completed_at timestamptz, result jsonb, notes text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.submission_tasks TO authenticated; GRANT ALL ON public.submission_tasks TO service_role; ALTER TABLE public.submission_tasks ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.submission_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task_id uuid NOT NULL, assignee_id uuid NOT NULL, assigned_by uuid, assigned_at timestamptz DEFAULT now() NOT NULL, status text DEFAULT 'active' NOT NULL, UNIQUE (task_id, assignee_id));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.submission_assignments TO authenticated; GRANT ALL ON public.submission_assignments TO service_role; ALTER TABLE public.submission_assignments ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.submission_delegations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task_id uuid NOT NULL, from_user_id uuid NOT NULL, to_user_id uuid NOT NULL, reason text, delegated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.submission_delegations TO authenticated; GRANT ALL ON public.submission_delegations TO service_role; ALTER TABLE public.submission_delegations ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.submission_escalations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task_id uuid NOT NULL, level integer DEFAULT 1 NOT NULL, reason text, escalated_to uuid, escalated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.submission_escalations TO authenticated; GRANT ALL ON public.submission_escalations TO service_role; ALTER TABLE public.submission_escalations ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.submission_sequences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), scope text NOT NULL, tahun integer NOT NULL, last_number integer DEFAULT 0 NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, UNIQUE (scope, tahun));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.submission_sequences TO authenticated; GRANT ALL ON public.submission_sequences TO service_role; ALTER TABLE public.submission_sequences ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.document_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id uuid, owner_opd_id uuid, opd_id uuid, code text, name text NOT NULL, description text, kind text DEFAULT 'html' NOT NULL, category text, template_html text, template_storage_path text, variables jsonb DEFAULT '[]'::jsonb NOT NULL, status text DEFAULT 'draft' NOT NULL, current_version integer DEFAULT 1 NOT NULL, current_version_id uuid, numbering_rule_id uuid, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, deleted_at timestamptz);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.document_templates TO authenticated; GRANT ALL ON public.document_templates TO service_role; ALTER TABLE public.document_templates ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.generated_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid, template_id uuid, storage_path text NOT NULL, mime text DEFAULT 'application/pdf' NOT NULL, size_bytes bigint, signed_document_id uuid, generated_at timestamptz DEFAULT now() NOT NULL, generated_by uuid, doc_number text, name text, status text DEFAULT 'generated' NOT NULL, template_version integer, snapshot jsonb DEFAULT '{}'::jsonb NOT NULL, archived_at timestamptz, numbering_rule_id uuid);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.generated_documents TO authenticated; GRANT ALL ON public.generated_documents TO service_role; ALTER TABLE public.generated_documents ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.form_audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid, action text NOT NULL, resource_type text NOT NULL, resource_id uuid, metadata jsonb DEFAULT '{}'::jsonb NOT NULL, ip_address inet, user_agent text, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.form_audit_logs TO authenticated; GRANT ALL ON public.form_audit_logs TO service_role; ALTER TABLE public.form_audit_logs ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.form_wizard_drafts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, form_id uuid, step text, payload jsonb DEFAULT '{}'::jsonb NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, title text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.form_wizard_drafts TO authenticated; GRANT ALL ON public.form_wizard_drafts TO service_role; ALTER TABLE public.form_wizard_drafts ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.workflow_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, code text, description text, category text, scope text DEFAULT 'opd' NOT NULL, owner_opd_id uuid, status text DEFAULT 'draft' NOT NULL, graph jsonb DEFAULT '{"nodes":[],"edges":[]}'::jsonb NOT NULL, definition jsonb DEFAULT '{}'::jsonb, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.workflow_templates TO authenticated; GRANT ALL ON public.workflow_templates TO service_role; ALTER TABLE public.workflow_templates ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.workflow_audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid, action text NOT NULL, resource_type text NOT NULL, resource_id uuid, metadata jsonb DEFAULT '{}'::jsonb NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.workflow_audit_logs TO authenticated; GRANT ALL ON public.workflow_audit_logs TO service_role; ALTER TABLE public.workflow_audit_logs ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.document_template_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), template_id uuid NOT NULL, version_number integer DEFAULT 1 NOT NULL, kind text DEFAULT 'html' NOT NULL, template_html text, template_storage_path text, variables jsonb DEFAULT '{}'::jsonb NOT NULL, content text, storage_path text, schema_snapshot jsonb DEFAULT '{}'::jsonb, published_at timestamptz, published_by uuid, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, UNIQUE (template_id, version_number));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.document_template_versions TO authenticated; GRANT ALL ON public.document_template_versions TO service_role; ALTER TABLE public.document_template_versions ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.document_numbering_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, name text NOT NULL, format text DEFAULT '{kode}/{seq}/{singkatan}/{tahun}' NOT NULL, scope text DEFAULT 'global' NOT NULL, category text, opd_id uuid, reset_period text DEFAULT 'yearly' NOT NULL, reset_per text DEFAULT 'yearly' NOT NULL, padding integer DEFAULT 6 NOT NULL, last_value integer DEFAULT 0 NOT NULL, status text DEFAULT 'active' NOT NULL, aktif boolean DEFAULT true NOT NULL, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.document_numbering_rules TO authenticated; GRANT ALL ON public.document_numbering_rules TO service_role; ALTER TABLE public.document_numbering_rules ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.document_numbering_sequences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rule_id uuid NOT NULL, scope_key text DEFAULT '' NOT NULL, year integer NOT NULL, last_number integer DEFAULT 0 NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, UNIQUE (rule_id, scope_key, year));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.document_numbering_sequences TO authenticated; GRANT ALL ON public.document_numbering_sequences TO service_role; ALTER TABLE public.document_numbering_sequences ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.document_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), document_id uuid NOT NULL, action text NOT NULL, actor_id uuid, metadata jsonb DEFAULT '{}'::jsonb NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.document_history TO authenticated; GRANT ALL ON public.document_history TO service_role; ALTER TABLE public.document_history ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.signature_providers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, name text NOT NULL, kind text NOT NULL, status text DEFAULT 'active' NOT NULL, config jsonb DEFAULT '{}'::jsonb NOT NULL, webhook_secret text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.signature_providers TO authenticated; GRANT ALL ON public.signature_providers TO service_role; ALTER TABLE public.signature_providers ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.signature_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), generated_document_id uuid, submission_id uuid, provider_id uuid, mode text DEFAULT 'sequential' NOT NULL, status text DEFAULT 'draft' NOT NULL, external_request_id text, file_hash text, current_step integer DEFAULT 0 NOT NULL, opd_id uuid, created_by uuid, sent_at timestamptz, completed_at timestamptz, cancelled_at timestamptz, error text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.signature_requests TO authenticated; GRANT ALL ON public.signature_requests TO service_role; ALTER TABLE public.signature_requests ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.signature_request_signers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), request_id uuid NOT NULL, order_index integer DEFAULT 0 NOT NULL, signer_type text DEFAULT 'user' NOT NULL, user_id uuid, role text, position text, opd_id uuid, status text DEFAULT 'pending' NOT NULL, external_signer_id text, signed_at timestamptz, rejected_at timestamptz, reject_reason text, parallel boolean DEFAULT false NOT NULL, deadline_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.signature_request_signers TO authenticated; GRANT ALL ON public.signature_request_signers TO service_role; ALTER TABLE public.signature_request_signers ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.signature_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), request_id uuid NOT NULL, signer_id uuid, event text NOT NULL, payload jsonb DEFAULT '{}'::jsonb NOT NULL, actor uuid, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.signature_events TO authenticated; GRANT ALL ON public.signature_events TO service_role; ALTER TABLE public.signature_events ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_submission_tasks_sub_status ON public.submission_tasks (submission_id, status);
CREATE INDEX IF NOT EXISTS idx_submission_assignments_assignee ON public.submission_assignments (assignee_id, status);
CREATE INDEX IF NOT EXISTS idx_generated_documents_submission ON public.generated_documents (submission_id);
CREATE INDEX IF NOT EXISTS idx_signature_requests_status ON public.signature_requests (status);
CREATE INDEX IF NOT EXISTS idx_signature_events_event_created ON public.signature_events (event, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_workflow_audit_resource ON public.workflow_audit_logs (resource_type, resource_id, created_at DESC);

INSERT INTO public.signature_providers (code,name,kind,status,config) VALUES ('mock','Mock Provider (Testing)','mock','active','{}'::jsonb), ('bsre','BSrE','bsre','disabled','{}'::jsonb), ('esign','e-Sign','esign','disabled','{}'::jsonb) ON CONFLICT (code) DO NOTHING;

DO $$ DECLARE r record; BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename IN ('form_versions','form_templates','workflow_definitions','workflow_versions','workflow_nodes','workflow_edges','submission_versions','submission_values','submission_tasks','submission_assignments','submission_delegations','submission_escalations','submission_sequences','document_templates','generated_documents','form_audit_logs','form_wizard_drafts','workflow_templates','workflow_audit_logs','document_template_versions','document_numbering_rules','document_numbering_sequences','document_history','signature_providers','signature_requests','signature_request_signers','signature_events') LOOP
    EXECUTE format('DROP POLICY IF EXISTS "auth_read_%s" ON public.%I', r.tablename, r.tablename);
    EXECUTE format('CREATE POLICY "auth_read_%s" ON public.%I FOR SELECT TO authenticated USING (true)', r.tablename, r.tablename);
    EXECUTE format('DROP POLICY IF EXISTS "admin_write_%s" ON public.%I', r.tablename, r.tablename);
    EXECUTE format('CREATE POLICY "admin_write_%s" ON public.%I FOR ALL TO authenticated USING (public.has_role(auth.uid(),''super_admin''::public.app_role) OR public.has_role(auth.uid(),''admin_opd''::public.app_role) OR public.has_role(auth.uid(),''admin_pemda''::public.app_role)) WITH CHECK (public.has_role(auth.uid(),''super_admin''::public.app_role) OR public.has_role(auth.uid(),''admin_opd''::public.app_role) OR public.has_role(auth.uid(),''admin_pemda''::public.app_role))', r.tablename, r.tablename);
  END LOOP;
END $$;