CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS pg_trgm;
DO $$ BEGIN CREATE TYPE public.employment_type AS ENUM ('PNS','PPPK','PPPK_PW','NON_ASN','THL'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS requested_role public.app_role,
  ADD COLUMN IF NOT EXISTS verification_status text DEFAULT 'pending_verification',
  ADD COLUMN IF NOT EXISTS verification_method text,
  ADD COLUMN IF NOT EXISTS rejected_at timestamptz,
  ADD COLUMN IF NOT EXISTS rejected_by uuid,
  ADD COLUMN IF NOT EXISTS rejection_reason text,
  ADD COLUMN IF NOT EXISTS alamat text,
  ADD COLUMN IF NOT EXISTS jabatan_id uuid,
  ADD COLUMN IF NOT EXISTS employment_type public.employment_type;
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_verification_status_chk;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_verification_status_chk CHECK (verification_status IS NULL OR verification_status IN ('pending','pending_verification','pending_superadmin_approval','verified','rejected','unverified'));

CREATE TABLE IF NOT EXISTS public.master_jabatan (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kode text UNIQUE, nama text NOT NULL, kategori text, pangkat_min text, golongan_min text, urutan integer DEFAULT 0 NOT NULL, aktif boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.master_jabatan TO authenticated; GRANT SELECT ON public.master_jabatan TO anon; GRANT ALL ON public.master_jabatan TO service_role; ALTER TABLE public.master_jabatan ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.branding (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text UNIQUE NOT NULL, value jsonb DEFAULT '{}'::jsonb NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, updated_by uuid);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.branding TO authenticated; GRANT ALL ON public.branding TO service_role; ALTER TABLE public.branding ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.aset_nilai_buku (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), aset_id uuid NOT NULL, periode text NOT NULL, nilai_perolehan numeric DEFAULT 0, akumulasi_penyusutan numeric DEFAULT 0, nilai_buku numeric DEFAULT 0, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.aset_nilai_buku TO authenticated; GRANT ALL ON public.aset_nilai_buku TO service_role; ALTER TABLE public.aset_nilai_buku ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.payroll_periods (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, tahun integer NOT NULL, bulan integer NOT NULL, locked_at timestamptz, locked_by uuid, unlocked_at timestamptz, unlocked_by uuid, catatan text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payroll_periods TO authenticated; GRANT ALL ON public.payroll_periods TO service_role; ALTER TABLE public.payroll_periods ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, tipe text NOT NULL, judul text NOT NULL, body text, link text, meta jsonb DEFAULT '{}'::jsonb, dibaca boolean DEFAULT false NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notifications TO authenticated; GRANT ALL ON public.notifications TO service_role; ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.overtime_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, opd_id uuid, tanggal date NOT NULL, jam_mulai time NOT NULL, jam_selesai time NOT NULL, alasan text, status text DEFAULT 'pending' NOT NULL, approved_by uuid, approved_at timestamptz, catatan_approval text, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.overtime_requests TO authenticated; GRANT ALL ON public.overtime_requests TO service_role; ALTER TABLE public.overtime_requests ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.pengajuan_izin (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, opd_id uuid, jenis text NOT NULL, dari date NOT NULL, sampai date NOT NULL, alasan text, lampiran_url text, status text DEFAULT 'pending' NOT NULL, approved_by uuid, approved_at timestamptz, catatan_approval text, mengurangi_saldo boolean DEFAULT false NOT NULL, saldo_terpotong integer DEFAULT 0 NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pengajuan_izin TO authenticated; GRANT ALL ON public.pengajuan_izin TO service_role; ALTER TABLE public.pengajuan_izin ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, label text NOT NULL, kategori text DEFAULT 'general' NOT NULL, description text, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.permissions TO authenticated; GRANT ALL ON public.permissions TO service_role; ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.permohonan_berkas (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), permohonan_id uuid NOT NULL, storage_path text NOT NULL, jenis text, nama_file text, size_bytes bigint, uploaded_by uuid, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.permohonan_berkas TO authenticated; GRANT ALL ON public.permohonan_berkas TO service_role; ALTER TABLE public.permohonan_berkas ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.rate_limit_hits (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), scope text NOT NULL, subject text NOT NULL, window_start timestamptz NOT NULL, count integer DEFAULT 1 NOT NULL, last_hit_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rate_limit_hits TO authenticated; GRANT ALL ON public.rate_limit_hits TO service_role; ALTER TABLE public.rate_limit_hits ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.rbac_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid, target_user_id uuid, action text NOT NULL, details jsonb DEFAULT '{}'::jsonb NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rbac_audit TO authenticated; GRANT ALL ON public.rbac_audit TO service_role; ALTER TABLE public.rbac_audit ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.retention_policies (entity text PRIMARY KEY, retention_days integer DEFAULT 365 NOT NULL, enabled boolean DEFAULT true NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, updated_by uuid, last_run_at timestamptz, last_deleted_count integer DEFAULT 0 NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.retention_policies TO authenticated; GRANT ALL ON public.retention_policies TO service_role; ALTER TABLE public.retention_policies ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.retry_queue (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_name text NOT NULL, payload jsonb DEFAULT '{}'::jsonb, status text DEFAULT 'pending' NOT NULL, attempts integer DEFAULT 0 NOT NULL, max_attempts integer DEFAULT 5 NOT NULL, last_attempt_at timestamptz, next_attempt_at timestamptz, next_run_at timestamptz, error text, last_error text, request_id text, locked_at timestamptz, locked_by text, completed_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.retry_queue TO authenticated; GRANT ALL ON public.retry_queue TO service_role; ALTER TABLE public.retry_queue ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.signing_certificates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, nip text, full_name text NOT NULL, position text, issued_at timestamptz DEFAULT now() NOT NULL, expired_at timestamptz, public_key text, is_active boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.signing_certificates TO authenticated; GRANT ALL ON public.signing_certificates TO service_role; ALTER TABLE public.signing_certificates ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.signed_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), document_id uuid NOT NULL, document_hash text NOT NULL, verification_token text NOT NULL UNIQUE, signed_by uuid NOT NULL, signed_at timestamptz DEFAULT now() NOT NULL, status text DEFAULT 'signed' NOT NULL, signed_file_path text NOT NULL, verification_count integer DEFAULT 0 NOT NULL, revoked_at timestamptz, revoke_reason text, expires_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.signed_documents TO authenticated; GRANT ALL ON public.signed_documents TO service_role; ALTER TABLE public.signed_documents ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.submission_dispositions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), permohonan_id uuid NOT NULL, from_user uuid NOT NULL, to_user uuid NOT NULL, level text NOT NULL, note text, status text DEFAULT 'pending' NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, acted_at timestamptz);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.submission_dispositions TO authenticated; GRANT ALL ON public.submission_dispositions TO service_role; ALTER TABLE public.submission_dispositions ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.submission_sla_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), permohonan_id uuid NOT NULL, event_type text NOT NULL, started_at timestamptz DEFAULT now() NOT NULL, ended_at timestamptz, duration_seconds integer, reason text, actor uuid, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.submission_sla_events TO authenticated; GRANT ALL ON public.submission_sla_events TO service_role; ALTER TABLE public.submission_sla_events ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.uat_scenarios (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), role text NOT NULL, modul text NOT NULL, description text NOT NULL, steps text[] DEFAULT '{}'::text[], enabled boolean DEFAULT true NOT NULL, code text, judul text, expected text, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.uat_scenarios TO authenticated; GRANT ALL ON public.uat_scenarios TO service_role; ALTER TABLE public.uat_scenarios ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.uat_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), scenario_id uuid NOT NULL, status text NOT NULL, catatan text, run_at timestamptz DEFAULT now() NOT NULL, run_by uuid, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.uat_results TO authenticated; GRANT ALL ON public.uat_results TO service_role; ALTER TABLE public.uat_results ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.user_permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, permission_code text NOT NULL, granted boolean DEFAULT true NOT NULL, expires_at timestamptz, reason text, granted_by uuid, revoked_at timestamptz, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_permissions TO authenticated; GRANT ALL ON public.user_permissions TO service_role; ALTER TABLE public.user_permissions ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.verification_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), target_type text NOT NULL, target_id uuid NOT NULL, actor_id uuid, action text NOT NULL, catatan text, meta jsonb DEFAULT '{}'::jsonb, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.verification_logs TO authenticated; GRANT ALL ON public.verification_logs TO service_role; ALTER TABLE public.verification_logs ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.work_schedule (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nama text NOT NULL, opd_id uuid, hari_kerja integer[] DEFAULT '{1,2,3,4,5}'::integer[] NOT NULL, jam_masuk time NOT NULL, jam_pulang time NOT NULL, toleransi_menit integer DEFAULT 15 NOT NULL, aktif boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.work_schedule TO authenticated; GRANT ALL ON public.work_schedule TO service_role; ALTER TABLE public.work_schedule ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.work_schedule_assignment (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, schedule_id uuid NOT NULL, berlaku_dari date DEFAULT CURRENT_DATE NOT NULL, berlaku_sampai date, created_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.work_schedule_assignment TO authenticated; GRANT ALL ON public.work_schedule_assignment TO service_role; ALTER TABLE public.work_schedule_assignment ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.notification_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_id uuid, channel text NOT NULL, key text NOT NULL, subject text, body text NOT NULL, variables jsonb DEFAULT '[]'::jsonb NOT NULL, enabled boolean DEFAULT true NOT NULL, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL, created_by uuid, UNIQUE (opd_id, channel, key));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notification_templates TO authenticated; GRANT ALL ON public.notification_templates TO service_role; ALTER TABLE public.notification_templates ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.laporan_ticket_sequence (tahun integer PRIMARY KEY, last_seq integer DEFAULT 0 NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.laporan_ticket_sequence TO authenticated; GRANT ALL ON public.laporan_ticket_sequence TO service_role; ALTER TABLE public.laporan_ticket_sequence ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.workflow_instances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id uuid, workflow_version_id uuid, submission_id uuid, status text DEFAULT 'running' NOT NULL, current_node text, context jsonb DEFAULT '{}'::jsonb, started_by uuid, started_at timestamptz DEFAULT now() NOT NULL, completed_at timestamptz, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.workflow_instances TO authenticated; GRANT ALL ON public.workflow_instances TO service_role; ALTER TABLE public.workflow_instances ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.workflows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, code text, status text DEFAULT 'draft' NOT NULL, definition jsonb DEFAULT '{}'::jsonb, created_by uuid, created_at timestamptz DEFAULT now() NOT NULL, updated_at timestamptz DEFAULT now() NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.workflows TO authenticated; GRANT ALL ON public.workflows TO service_role; ALTER TABLE public.workflows ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE VIEW public.v_permohonan_overdue AS SELECT p.id, p.kode, p.judul, p.opd_id, p.status, p.tanggal_masuk, p.tenggat, EXTRACT(EPOCH FROM (now() - p.tenggat))::integer AS overdue_seconds FROM public.permohonan p WHERE p.tenggat IS NOT NULL AND p.tenggat < now() AND p.status NOT IN ('selesai','ditolak');
GRANT SELECT ON public.v_permohonan_overdue TO authenticated, service_role;

CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON public.notifications (user_id, created_at DESC) WHERE dibaca = false;
CREATE INDEX IF NOT EXISTS idx_permohonan_berkas_permohonan ON public.permohonan_berkas (permohonan_id);
CREATE INDEX IF NOT EXISTS idx_rate_limit_hits_window ON public.rate_limit_hits (scope, subject, window_start);

DO $$ DECLARE r record; BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename IN ('master_jabatan','branding','aset_nilai_buku','payroll_periods','notifications','overtime_requests','pengajuan_izin','permissions','permohonan_berkas','rate_limit_hits','rbac_audit','retention_policies','retry_queue','signing_certificates','signed_documents','submission_dispositions','submission_sla_events','uat_scenarios','uat_results','user_permissions','verification_logs','work_schedule','work_schedule_assignment','notification_templates','laporan_ticket_sequence','workflow_instances','workflows') LOOP
    EXECUTE format('DROP POLICY IF EXISTS "auth_read_%s" ON public.%I', r.tablename, r.tablename);
    EXECUTE format('CREATE POLICY "auth_read_%s" ON public.%I FOR SELECT TO authenticated USING (true)', r.tablename, r.tablename);
    EXECUTE format('DROP POLICY IF EXISTS "admin_write_%s" ON public.%I', r.tablename, r.tablename);
    EXECUTE format('CREATE POLICY "admin_write_%s" ON public.%I FOR ALL TO authenticated USING (public.has_role(auth.uid(),''super_admin''::public.app_role) OR public.has_role(auth.uid(),''admin_opd''::public.app_role) OR public.has_role(auth.uid(),''admin_pemda''::public.app_role)) WITH CHECK (public.has_role(auth.uid(),''super_admin''::public.app_role) OR public.has_role(auth.uid(),''admin_opd''::public.app_role) OR public.has_role(auth.uid(),''admin_pemda''::public.app_role))', r.tablename, r.tablename);
  END LOOP;
END $$;
DROP POLICY IF EXISTS "master_jabatan_read_public" ON public.master_jabatan;
CREATE POLICY "master_jabatan_read_public" ON public.master_jabatan FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "notifications_own" ON public.notifications;
CREATE POLICY "notifications_own" ON public.notifications FOR ALL TO authenticated USING (user_id = auth.uid() OR public.has_role(auth.uid(),'super_admin'::public.app_role)) WITH CHECK (user_id = auth.uid() OR public.has_role(auth.uid(),'super_admin'::public.app_role));